# Generated by Django 5.2.17 on 2026-09-19 18:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('parties', '0001_initial'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=30, unique=True)),
                ('purchase_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rate_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('freight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='currencies.currency')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='parties.party')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['purchase_date', 'document_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchase')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_line_qty_gt0'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_line_price_gte0'), models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='purchase_line_total_gte0'), models.CheckConstraint(condition=models.Q(('discount_allocated__gte', 0)), name='purchase_line_discount_gte0'), models.CheckConstraint(condition=models.Q(('net_total__gte', 0)), name='purchase_line_net_gte0')],
            },
        ),
    ]
