# Generated by Django 5.2.17 on 2026-09-14 19:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=20)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('ref_purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('ref_sales_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=20)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
                ('primary_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_products', to='uom.unitofmeasure')),
                ('secondary_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_products', to='uom.unitofmeasure')),
            ],
            options={
                'ordering': ['code', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='prod_code_nonblank'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='prod_name_nonblank'), models.CheckConstraint(condition=models.Q(('name_fa', ''), _negated=True), name='prod_namefa_nonblank'), models.CheckConstraint(condition=models.Q(('conversion_factor__gt', 0)), name='prod_factor_gt0'), models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='prod_min_gte0')],
            },
        ),
    ]
