# Generated by Django 5.2.17 on 2026-09-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name_fa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
