# Generated by Django 5.2.17 on 2026-09-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_backfill_journal_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='accounting.journalentry'),
        ),
    ]
