# Generated by Django 5.2.17 on 2026-09-10 19:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_source_trace_index'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FXSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('kind', models.CharField(default='CONVERSION', max_length=12)),
                ('source_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('settlement_rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rate_direction', models.CharField(max_length=20)),
                ('historical_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('carrying_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('settlement_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('direction', models.CharField(choices=[('GAIN', 'Gain'), ('LOSS', 'Loss'), ('NONE', 'No FX result')], default='NONE', max_length=8)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fx_settlement', to='accounting.journalentry')),
                ('fx_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fx_settlement_results', to='accounting.account')),
                ('obligation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_settlement_obligations', to='accounting.account')),
                ('settlement_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_settlement_destinations', to='accounting.account')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_settlement_sources', to='currencies.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_settlement_targets', to='currencies.currency')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['transaction_date'], name='fx_settle_date_idx')],
            },
        ),
    ]
