# Generated by Django 5.2.17 on 2026-09-16 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0007_fx_settlement_record'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyLedgerAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='party_ledger_attribution', to='accounting.journalline')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_ledger_attributions', to='parties.party')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
