# Generated by Django 5.2.17 on 2026-09-06 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('is_base', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('is_base',), name='one_base_currency')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('effective_date', models.DateField()),
                ('source', models.CharField(default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_as_source', to='currencies.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_as_target', to='currencies.currency')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='positive_exchange_rate'), models.CheckConstraint(condition=models.Q(('source_currency', models.F('target_currency')), _negated=True), name='different_exchange_currencies'), models.UniqueConstraint(fields=('source_currency', 'target_currency', 'effective_date'), name='unique_rate_per_pair_date')],
            },
        ),
    ]
