# Generated by Django 5.2.17 on 2026-09-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fa', models.CharField(blank=True, default='', max_length=200)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='party_name_nonblank'), models.CheckConstraint(condition=models.Q(('is_customer', True), ('is_supplier', True), _connector='OR'), name='party_has_role')],
            },
        ),
    ]
