# Generated by Django 5.2.17 on 2026-09-18 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0007_fx_settlement_record'),
        ('currencies', '0001_initial'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInventoryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_inventory_links', to='accounting.account')),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_account', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['warehouse_id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALES_ISSUE', 'Sales Issue'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('OPENING', 'Opening')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('movement_date', models.DateField()),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rate_date', models.DateField()),
                ('unit_cost_afn', models.DecimalField(decimal_places=4, max_digits=20)),
                ('is_temporary_cost', models.BooleanField(default=False)),
                ('qty_before', models.IntegerField()),
                ('qty_after', models.IntegerField()),
                ('reference', models.CharField(max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='currencies.currency')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='accounting.journalentry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['movement_date', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__lt', 0), _connector='OR'), name='inv_movement_qty_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', frozenset(['ADJUSTMENT_IN', 'OPENING', 'PURCHASE_RECEIPT', 'SALES_RETURN', 'TRANSFER_IN'])), ('quantity__gt', 0)), models.Q(('movement_type__in', frozenset(['ADJUSTMENT_OUT', 'PURCHASE_RETURN', 'SALES_ISSUE', 'TRANSFER_OUT'])), ('quantity__lt', 0)), _connector='OR'), name='inv_movement_direction'), models.CheckConstraint(condition=models.Q(('reference', ''), _negated=True), name='inv_movement_reference_nonblank'), models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inv_movement_unit_cost_gte0'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='inv_movement_rate_gt0')],
            },
        ),
    ]
