# Generated by Django 5.2.17 on 2026-09-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_fx_settlement_record'),
        ('currencies', '0001_initial'),
        ('inventory', '0002_stockmovement_description'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortageSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField()),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rate_date', models.DateField()),
                ('compensation_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('reference', models.CharField(max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['settlement_date', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='inv_movement_direction',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='gross_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='waste_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALES_ISSUE', 'Sales Issue'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('SHORTAGE', 'Shortage'), ('OPENING', 'Opening')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', frozenset(['ADJUSTMENT_IN', 'OPENING', 'PURCHASE_RECEIPT', 'SALES_RETURN', 'TRANSFER_IN'])), ('quantity__gt', 0)), models.Q(('movement_type__in', frozenset(['ADJUSTMENT_OUT', 'PURCHASE_RETURN', 'SALES_ISSUE', 'SHORTAGE', 'TRANSFER_OUT'])), ('quantity__lt', 0)), _connector='OR'), name='inv_movement_direction'),
        ),
        migrations.AddField(
            model_name='shortagesettlement',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shortage_settlements', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='shortagesettlement',
            name='shortage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='inventory.stockmovement'),
        ),
        migrations.AddConstraint(
            model_name='shortagesettlement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_rate__gte', 0)), name='inv_settle_rate_gte0'),
        ),
        migrations.AddConstraint(
            model_name='shortagesettlement',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='inv_settle_rate_gt0'),
        ),
    ]
