# Generated by Django 5.2.17 on 2026-09-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shortagesettlement_and_more'),
        ('parties', '0001_initial'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('PURCHASE_RETURN', 'Purchase Return'), ('SALES_RETURN', 'Sales Return')], max_length=20)),
                ('source_document', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_returns', to='parties.party')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_returns', to='products.product')),
                ('return_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_record', to='inventory.stockmovement')),
                ('source_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.stockmovement')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_returns', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inv_return_qty_gt0'), models.CheckConstraint(condition=models.Q(('source_document', ''), _negated=True), name='inv_return_source_nonblank')],
            },
        ),
    ]
